---
- name: Restart OpenSearch
  service:
    name: opensearch
    enabled: yes
    state: restarted

- name: Restart Graylog
  service:
    name: graylog-server
    enabled: yes
    state: restarted
